### ISSUE TITLE
the last qubes-gui-agent update broke my ability to run graphical applications

### ISSUE THREAD

**Issue by colons** [fepitre/qubes-gentoo#14]
after the bundle of updates on feb 21 (a1544c532ee1a4f0e0bfd4ff657891e73ae00258...5ed29b3c906436801b8e74dde05b1304a6f65569), i became unable to run graphical applications in my gentoo template. when run from a Xen console, things like xterm would fail to connect to display `:0`. i didn't have time to do a lot of debugging at the time, so i just reverted the repo to before those changes and then disabled autoupdates for it

i recently had a moment to look into it, so i did a bisect (rebuilding `@world` and rebooting each time), and learned that this starts being broken at commit dee19b42c9e8e84aedab77c815a13c2579002c28, which i think means it might be a bug or incompatibility with qubes-gui-agent?

sorry for the delay here, and also for the lack of actionable information. i do not know how to debug this further, but i am happy to; what log files should i be looking at when it's failing, for example?

**Comment by fepitre** [comment]
I guess you have not do that https://forum.qubes-os.org/t/new-gentoo-templates-and-maintenance-infrastructure/961/9?u=fepitre?

**Comment by colons** [comment]
oh! i read through the whole thread. i guess you mean [this post specifically](https://forum.qubes-os.org/t/new-gentoo-templates-and-maintenance-infrastructure/961/9?u=fepitre#post_9)? i'll try that in a bit

i'd ask that you please add [news items](https://www.gentoo.org/glep/glep-0042.html) to the repo (by dropping them in `metadata/news`) in future for potentially breaking changes like this. that's where gentoo users are told to expect information like that. i don't know how i was supposed to know to check this years-old forum thread

**Comment by fepitre** [comment]
> oh! i read through the whole thread. i guess you mean [this post specifically](https://forum.qubes-os.org/t/new-gentoo-templates-and-maintenance-infrastructure/961/9?u=fepitre#post_9)? i'll try that in a bit

Yes

> i'd ask that you please add [news items](https://www.gentoo.org/glep/glep-0042.html) to the repo (by dropping them in `metadata/news`) in future for potentially breaking changes like this. that's where gentoo users are told to expect information like that. i don't know how i was supposed to know to check this years-old forum thread

Thank you for the tip.

**Comment by colons** [comment]
> Yes, this is what the link provided refers to.

oh there's some javascript here. sorry. without js, that's just a link to the thread; it does not scroll to or highlight any particular reply. i am not sure why discourse doesn't use fragment links for this, but that's not on you

**Comment by colons** [comment]
okay yes! setting that repo to the 4.1 branch has worked. i have re-enabled auto-sync and all seems well. thanks for your help!

**Comment by colons** [comment]
(i guess it might still be worth adding a news item about this change specifically; i had been waiting for another update since this broke for me, and a news item would have helped even if i was rolling back the changes after each sync that didn't have anything new)
