### ISSUE TITLE
Out of date packages in `release4.1` branch

### ISSUE THREAD

**Issue by Tonux599** [fepitre/qubes-gentoo#16]
I was going to open another issue about [cursor icon passthrough](https://github.com/QubesOS/qubes-issues/issues/1551) not working on my custom built xfce template based on the latest gentoo minimal community template. However before tackling that I noticed at least one package in the `release4.1` branch is very, very out of date.

It seems `qubes-core-agent-linux` is on `v4.1.37`, about a year old. The latest for R4.1 is [`v4.1.44`](https://github.com/QubesOS/updates-status/issues?q=is%3Aissue+is%3Aclosed+%22qubes-core-agent-linux%22+%22%28r4.1%29%22)

I see the `release4.2` branch is seeing more recent commits. Is it possible that the `release4.1` branch can continued to be maintained until R4.1 is EOL? (or at least until R4.2 is out of testing).

**Comment by fepitre** [comment]
I updated the overlay. There is no automatic updates, it's just me thinking to updating stuff. Please note that for now the Gentoo template does work under R4.2. I've not yet had enough time to going more through this.

**Comment by Tonux599** [comment]
Great, thank you!

I'm still quite new to Gentoo, but if I understand these ebuild files correctly, using package version 9999 will build from the latest commit in `release4.1` branch? I'm not sure if that branch is only updated on version release. If so I wonder if this could be made the default behavior somehow? Or if a ebuild file could be written in such a way to use the latest v4.1.* tag in that branch?

**Comment by fepitre** [comment]
9999 version would use always latest commits from Qubes `release4.1` repositories and it means possibly having not stable at all components. If you don't want to remain on version tags, you can adjust your system to use 9999 version for qubes components. Take a look at Gentoo documentation for that.
