### ISSUE TITLE
`qubes-core-qrexec-4.1.32` build fails in qubes 4.1 with "portageq is not allowed in ebuild scope"

### ISSUE THREAD

**Issue by colons** [fepitre/qubes-gentoo#19]
sorry if you're already tracking this. probably related: https://bugs.gentoo.org/916296

```
>>> Preparing source in /var/tmp/portage/app-emulation/qubes-core-qrexec-4.1.23/work/qubes-core-qrexec-4.1.23 ...
 * ERROR: app-emulation/qubes-core-qrexec-4.1.23::qubes failed (prepare phase):
 *   portageq is not allowed in ebuild scope
 * 
 * Call stack:
 *          ebuild.sh, line  136:  Called src_prepare
 *        environment, line 4555:  Called qubes_verify_sources_git 'v4.1.23'
 *        environment, line 4430:  Called portageq 'get_repo_path' '/' 'qubes'
 *   phase-helpers.sh, line 1010:  Called die
 * The specific snippet of code:
 *   	die "portageq is not allowed in ebuild scope"
 ```

you can work around this by replacing the `portageq` invocation in `eclass/qubes.eclass` with a hard-coded path to your qubes repo, but that's not ideal for a number of reasons (and the build still fails due to the `_FORTIFY_SOURCE` redefinition talked about in #12, which requires additional patching)

**Comment by lubellier** [comment]
I saw the same issue today. 
A new xorg update [activated](https://github.com/fepitre/qubes-gentoo/blob/release4.1/app-emulation/qubes-gui-agent/.qubes-gui-agent.ebuild.0#L33) a qubes-gui-agent re-build which raised the above error message.
Portageq is deprecated in the eclass scope. I'm searching how to replace the  `portageq` usage  in [qubes.eclass](https://github.com/fepitre/qubes-gentoo/blob/release4.1/eclass/qubes.eclass#L6)...

**Comment by lubellier** [comment]
> I'm searching how to replace the portageq usage in qubes.eclass...

I only found hacks:

1. hardcoded absolute path (i.e. :  `QUBES_OVERLAY_DIR="/var/db/repos/qubes"`), [see](https://github.com/InBetweenNames/gentooLTO/issues/883#issuecomment-1779821970)
2. portageq full path (i.e. : `QUBES_OVERLAY_DIR="$(/usr/bin/portageq get_repo_path / qubes)"`), [see](https://github.com/InBetweenNames/gentooLTO/issues/883#issuecomment-1780246180)

and the least-worst solution : 

1. a default path with an available override, see the [gentooLTO workaround](https://github.com/InBetweenNames/gentooLTO/commit/21d2ba49bde2180972513b878b768c6e1bddaa7c)

Someone with a better solution ?

Resources:
1. https://github.com/InBetweenNames/gentooLTO/issues/883

**Comment by lubellier** [comment]
@colons could you test the now updated repository? And if solved, close this issue.

**Comment by colons** [comment]
stuff still doesn't build (due to #12), but yes this issue appears to be solved. thank you
