### ISSUE TITLE
qubes-gui-agent build fails becasue v4.2.11 upstream lacks libpulse 17 headers

### ISSUE THREAD

**Issue by alimirjamali** [fepitre/qubes-gentoo#21]
After upgrading @world on my gentoo-minimal template, libpulse is upgraded to v17.0.
It appears that the [upstream version bump](https://gitweb.gentoo.org/repo/gentoo.git/commit/media-libs/libpulse/libpulse-17.0.ebuild?id=e439181afa83acc45c62ef584f7d03009e75c0ba) happened on 2nd February.

Currently qubes-gui-agent v4.2.11 is selected in the ebuild which [lacks libpulse 17](https://github.com/QubesOS/qubes-gui-agent-linux/tree/v4.2.11/pulse).

Subsequently [ebuild selects v17 for libpulse and creates symlink to non-existence pulsecore directory](https://github.com/fepitre/qubes-gentoo/blob/7f2999d483a2f7ea5afecbc7c3174ba0308cb859/app-emulation/qubes-gui-agent/.qubes-gui-agent.ebuild.0#L60).

Suggested solution: Bump the upstream branch to ~~4.2.13~~?
p.s.: v4.2.13 builds successfully but audio is missing. Reverting to 4.2.12 and will report back. Also all other packages will be tested against latest upstream branches tagged "successful"

Thanks a lot.

**Comment by alimirjamali** [comment]
Update: It appears that the issue with sound system is more complex, probably not related to qubes-gui-agent 4.2.13 or 4.2.12 (both compile & install fine). ~~/dev/xvdd is also missing and not mounted~~. I have to study Audio virtualisation  mechanism in order to see if I could provide useful information. Otherwise it would be waste of your valuable time.

More clarification: Qubes OS 4.2

BTW,  I wonder if such issues would be better reported here or on https://github.com/QubesOS/qubes-issues ?

**Comment by alimirjamali** [comment]
Update: Audio is working with pipewire. I had to remove pulseaudio (keeping libpulse), install pipwire and enable required services. I wonder if there is proper instructions for other users in the forum and/or wiki. I will submit my changes for review.

This issue could be closed. Thanks again for your work.

**Comment by fepitre** [comment]
> Update: It appears that the issue with sound system is more complex, probably not related to qubes-gui-agent 4.2.13 or 4.2.12 (both compile & install fine). ~/dev/xvdd is also missing and not mounted~. I have to study Audio virtualisation mechanism in order to see if I could provide useful information. Otherwise it would be waste of your valuable time.
> 
> More clarification: Qubes OS 4.2
> 
> BTW, I wonder if such issues would be better reported here or on https://github.com/QubesOS/qubes-issues ?

Yes exactly, you can report further issues or request for features there. Thank you.

**Comment by fepitre** [comment]
I've upgraded overlay on `release-4.2` branch. Does it help?
