### ISSUE TITLE
The qubes-core-agent-linux package update failed with the PYTHON_TARGETS version 12

### ISSUE THREAD

**Issue by lubellier** [fepitre/qubes-gentoo#23]
## The problem

The qubes-core-agent-linux package update failed with a PYTHON_TARGETS problem.
```
Calculating dependencies \

!!! Problem resolving dependencies for app-emulation/qubes-core-agent-linux from @selected
... done!
Dependency resolution took 0.95 s (backtrack: 0/20).


!!! The ebuild selected to satisfy "app-emulation/qubes-core-agent-linux" has unmet requirements.
- app-emulation/qubes-core-agent-linux-4.2.29::qubes USE="networking -nautilus -network-manager -pandoc-bin -passwordless-root" ABI_X86="(64)" PYTHON_TARGETS="-python3_10 -python3_11"

  The following REQUIRED_USE flag constraints are unsatisfied:
    any-of ( python_targets_python3_10 python_targets_python3_11 )

(dependency required by "@selected" [set])
(dependency required by "@world" [argument])

```

## The solution
same as the https://github.com/fepitre/qubes-gentoo/issues/10 issue solved with the https://github.com/fepitre/qubes-gentoo/commit/63a7e997024fbc6280b17ce1ad2418bb8538e05f commit, update the PYTHON_COMPAT:
- from ```PYTHON_COMPAT=( python3_{7..11} )```
- to `PYTHON_COMPAT=( python3_{10..13} )`

Why 13 and not 12? Because python-3.13 is the next... Others gentoo packages already uses the 3.13 target ([docutils example](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/docutils)).

**Comment by lubellier** [comment]
see the published  https://github.com/fepitre/qubes-gentoo/pull/24

**Comment by fepitre** [comment]
I guess we can close. Thank you for your #24.
