### ISSUE TITLE
qubes-pdf-converter, qubes-thunderbird, and qubes-img-converter seem to have incorrect manifests

### ISSUE THREAD

**Issue by colons** [fepitre/qubes-gentoo#26]
sorry if i've missed something here. im in `release4.2`

in the changes between d753931cdbf0dd014a2e4ac0aa9c6acd0e3cfffe...d8e8969b3cfbc4b923ae8399349ba1daabe3cdb6, the size and checksums of some ebuilds that don't appear to have changed in content were updated. `qubes-pdf-converter`, `qubes-thunderbird`, and `qubes-img-converter`, though, were not touched and currently seem to have incorrect size and checksums. in order to get these packages to build, i had to alter the filesize and checksums in the manifests manually, otherwise i get errors like:

```
!!! Digest verification failed:
!!! /var/db/repos/qubes/app-emulation/qubes-thunderbird/qubes-thunderbird-2.0.6.ebuild
!!! Reason: Filesize does not match recorded size
!!! Got: 866
!!! Expected: 865
```

for what it's worth, `wc` agrees with emerge here. am i doing something wrong?

**Comment by colons** [comment]
i'm still getting

```
 * Digest verification failed:
 * /var/db/repos/qubes/app-emulation/qubes-thunderbird/qubes-thunderbird-2.0.8.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 866
 * Expected: 865
```

as of c83d3e6df5f23e4a7e2f55edb512b251df38c4ae. is it just me this is happening to? the manifest still disagrees with `wc -c`, `sha256sum`, and `b2sum`, and git is happy that my `/var/db/repos/qubes/` is clean. cloning the repo and checking from a different vm shows the same mismatch

**Comment by cyberguerilla68** [comment]
Same for me

**Comment by fepitre** [comment]
Sorry, I missed it. I forced Manifest regeneration. My toolset is not perfect and I don't know why it did not detected a change at first. Sorry. Please tell me if it is now ok.

**Comment by colons** [comment]
seems fixed to me. thank you
