### ISSUE TITLE
pulseaudio compatibility conflicts with pipewire

### ISSUE THREAD

**Issue by ctr49** [fepitre/qubes-gentoo#30]
The current (release4.2) `qubes-gui-agent` depends on both `media-sound/pulseaudio` and `media-sound/pipewire`. However, `media-sound/pulseaudio` is a ([deprecated](media-sound/pulseaudio)) wrapper for `media-sound/pulseaudio-daemon` which is blocking `media-sound/pipewire`.
According to https://wiki.gentoo.org/wiki/PipeWire#USE_flags `media-sound/pulseaudio-daemon` should be removed when using pipewire. So I think the DEPEND to `media-sound/pulseaudio` should be removed or - if pulseaudio libraries are still needed - replaced by `media-libs/libpulse`.

**Comment by fepitre** [comment]
Is your PR enough to fix that?

**Comment by ctr49** [comment]
I had to manually remove `media-sound/pipewire` but I don't think this can be avoided. Otherwise the updated ebuild was pulled and compiled & installed just fine.

**Comment by fepitre** [comment]
Great, closing it if the update works. Thank you.
